### ISSUE TITLE
Internal Exceptions Not handled right leading to app crash

### ISSUE THREAD

**Issue by thehellmaker** [andriydruk/RxDNSSD#159]
I have integrated the library into react-native native module. I have caught all sorts of exceptions possible but when Wifi is not connects Nsd init is throwing an exception which I am not able to catch. Looks like an exception is not handled right internally

Here is the pull request will all the implementation for the same 
https://github.com/balthazar/react-native-zeroconf/pull/131
https://github.com/thehellmaker/react-native-zeroconf/blob/master/android/src/main/java/com/balthazargronon/RCTZeroconf/rx2dnssd/DnssdImpl.java

E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    Process: com.atom8.app, PID: 22573
    io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: Interrupted wait at init
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:276)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:75)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableDoFinally.subscribeActual(FlowableDoFinally.java:46)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.Flowable.subscribe(Flowable.java:14425)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.RuntimeException: Interrupted wait at init
        at android.net.nsd.NsdManager.fatal(NsdManager.java:520)
        at android.net.nsd.NsdManager.init(NsdManager.java:514)
        at android.net.nsd.NsdManager.<init>(NsdManager.java:271)
        at android.app.SystemServiceRegistry$34.createService(SystemServiceRegistry.java:523)
        at android.app.SystemServiceRegistry$34.createService(SystemServiceRegistry.java:518)
        at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1410)
        at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1326)
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1839)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:752)
        at com.github.druk.dnssd.DNSSDBindable.onServiceStarting(DNSSDBindable.java:39)
        at com.github.druk.dnssd.DNSSD.browse(DNSSD.java:140)
        at com.github.druk.rx2dnssd.Rx2DnssdCommon.lambda$browse$0$Rx2DnssdCommon(Rx2DnssdCommon.java:50)
        at com.github.druk.rx2dnssd.-$$Lambda$Rx2DnssdCommon$3I8oCO7uasGWk5oEmgRExhX07GY.getService(Unknown Source:6)
        at com.github.druk.rx2dnssd.Rx2DnssdCommon$DNSSDServiceAction.subscribe(Rx2DnssdCommon.java:247)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableDoFinally.subscribeActual(FlowableDoFinally.java:46) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14425) 
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by MauliVolansys** [comment]
@andriydruk when is the new version of the library coming with this fix?

**Comment by andriydruk** [comment]
Hi, version 0.9.14 in JCenter
