### ISSUE TITLE
Issue when starting Release APK (not in debug/staging)

### ISSUE THREAD

**Issue by alissongodoi** [andriydruk/RxDNSSD#32]
After compiling the app and installing it on the Android Emulator 6.0 it crashes with the following error on startup:

```
java.lang.InternalError: cannot instantiate DNSSDjava.lang.ClassNotFoundException: com.github.druk.dnssd.AppleDNSSD
                                                                           at com.b.a.a.h.<clinit>(Unknown Source)
                                                                           at com.b.a.a.b.<init>(Unknown Source)
                                                                           at com.b.a.a.b.<init>(Unknown Source)
                                                                           at com.b.a.a.c.<init>(Unknown Source)
                                                                           at com.yourock.digitaltv.coordinator.CoordinatorService.<clinit>(Unknown Source)
                                                                           at java.lang.Class.newInstance(Native Method)
                                                                           at android.app.ActivityThread.handleCreateService(ActivityThread.java:2859)
                                                                           at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by alissongodoi** [comment]
I have noticed that the issue goes away when minify is disabled. 
I have no idea why minify is causing this issue in the release build.

**Comment by alissongodoi** [comment]
#Minify was removing the druk classes for some reason
#Forcing it to stay in the release package.
-dontwarn com.github.druk.**
-keep class com.github.druk.** { *; }

**Comment by andriydruk** [comment]
@alissongodoi Proguard make obfuscation of all you classes. It's rename all of them to a.b.c.d.etc.
You are not first person who face this problem.

Maybe I should ship AAR with proguard rules inside. I'm going to investigate if it's possible

**Comment by G00fY2** [comment]
@andriydruk: Should be possible with [consumerProguardFiles](https://developer.android.com/studio/projects/android-library.html#Considerations). Otherwise I would recommend maybe put the rules in the readme (like in [retrofit](https://github.com/square/retrofit)).

**Comment by skykelsey** [comment]
As mentioned by @G00fY2, you should be able to just add a file called `consumer-proguard-rules.pro` in the same directory as your `build.gradle`. Then, add this line in `build.gradle` in `defaultConfig`:

`consumerProguardFiles 'consumer-proguard-rules.pro'`

I can open a PR if you'd like.

**Comment by Abu-Abdullah** [comment]
i believe you need to keep rx.* as well:
```
-keep class com.github.druk.** { *; }
-keep class rx.** { *; }
```

**Comment by tmm1** [comment]
> I can open a PR if you'd like.

Please do this.

**Comment by leohuangyi** [comment]
-keep class com.github.druk.dnssd.** { *; } 

work well!
