### ISSUE TITLE
Wrong txtRecord format will crash app.

### ISSUE THREAD

**Issue by NeoLSN** [andriydruk/RxDNSSD#5]
```
java.lang.ArrayIndexOutOfBoundsException: src.length=38 srcPos=3 dst.length=103 dstPos=0 length=103
                                                                         at java.lang.System.arraycopy(Native Method)
                                                                         at com.apple.dnssd.TXTRecord.getValue(TXTRecord.java:219)
                                                                         at com.apple.dnssd.TXTRecord.getValueAsString(TXTRecord.java:230)
                                                                         at com.github.druk.rxdnssd.RxResolveListener.parseTXTRecords(RxResolveListener.java:57)
                                                                         at com.github.druk.rxdnssd.RxResolveListener.serviceResolved(RxResolveListener.java:42)
                                                                         at com.apple.dnssd.AppleService.ProcessResults(Native Method)
                                                                         at com.apple.dnssd.AppleService.run(DNSSD.java:693)
                                                                         at java.lang.Thread.run(Thread.java:818)
```
Do you have any idea about this?

**Comment by NeoLSN** [comment]
Seems it happened when the txtRecord is in the wrong format.
I can not catch the exception by app.
It will crash app.

**Comment by NeoLSN** [comment]
Where can I get a snapshot version to test?

**Comment by andriydruk** [comment]
I published new version to JCenter

`compile 'com.github.andriydruk:rxdnssd:0.8.1'`

**Comment by NeoLSN** [comment]
Thanks.
