### ISSUE TITLE
0.9.11 crashing

### ISSUE THREAD

**Issue by elevenfive** [andriydruk/RxDNSSD#50]
After upgrading to 0.9.11 yesterday I saw two new crashes, that go away after reverting back to 0.9.10:

```
W/System.err: io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: MulticastLock under-locked com.github.druk.dnssd.DNSSD
W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.runFinally(FlowableDoFinally.java:149)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.onComplete(FlowableDoFinally.java:96)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.complete(FlowableCreate.java:267)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.drain(FlowableCreate.java:543)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableCreate$BufferAsyncEmitter.onComplete(FlowableCreate.java:498)
W/System.err:     at com.github.druk.rx2dnssd.Rx2QueryListener.queryAnswered(Rx2QueryListener.java:59)
W/System.err:     at com.github.druk.dnssd.DNSSD$4.lambda$queryAnswered$0$DNSSD$4(DNSSD.java:423)
W/System.err:     at com.github.druk.dnssd.DNSSD$4$$Lambda$0.run(Unknown Source:18)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
```

and

```
W/System.err: io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: MulticastLock under-locked com.github.druk.dnssd.DNSSD
W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.runFinally(FlowableDoFinally.java:149)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.cancel(FlowableDoFinally.java:102)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.cancel(FlowableFlatMap.java:353)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.cancel(FlowableFlatMap.java:353)
W/System.err:     at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:189)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.cancel(FlowableSubscribeOn.java:141)
W/System.err:     at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.cancel(FlowableObserveOn.java:154)
W/System.err:     at io.reactivex.internal.subscriptions.SubscriptionArbiter.drainLoop(SubscriptionArbiter.java:218)
W/System.err:     at io.reactivex.internal.subscriptions.SubscriptionArbiter.drain(SubscriptionArbiter.java:187)
W/System.err:     at io.reactivex.internal.subscriptions.SubscriptionArbiter.cancel(SubscriptionArbiter.java:179)
W/System.err:     at io.reactivex.internal.subscriptions.SubscriptionArbiter.drainLoop(SubscriptionArbiter.java:218)
W/System.err:     at io.reactivex.internal.subscriptions.SubscriptionArbiter.drain(SubscriptionArbiter.java:187)
W/System.err:     at io.reactivex.internal.subscriptions.SubscriptionArbiter.cancel(SubscriptionArbiter.java:179)
W/System.err:     at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:189)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.cancel(LambdaSubscriber.java:119)
W/System.err:     at io.reactivex.internal.subscribers.LambdaSubscriber.dispose(LambdaSubscriber.java:104)
W/System.err:     at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:235)
W/System.err:     at io.reactivex.disposables.CompositeDisposable.dispose(CompositeDisposable.java:80)

```

**Comment by Abu-Abdullah** [comment]
the same for me. there is an issue with this fix https://github.com/andriydruk/RxDNSSD/commit/6a4476765def409a82965f444f57ea577ecdcb40

**Comment by vaiden** [comment]
Happens here as well.

**Comment by abangerl** [comment]
A fix for this bug would be great.

**Comment by Abu-Abdullah** [comment]
it works again now

**Comment by andriydruk** [comment]
I'm closing this issue. If `MulticastLock under-locked` still occurs, please reopen it 🙏

**Comment by elevenfive** [comment]
Yes appears fine. Thank you!
