### ISSUE TITLE
MulticastLock under-locked  and Too many open files

### ISSUE THREAD

**Issue by githubforzjm** [andriydruk/RxDNSSD#59]
Hi, Andriy Druk 
    First of all, thanks for your RxDNSSD open source library using Apple mDNS and the help you provided.

  I have some questions that you need to confirm below:
    When there are 30 services on the network, I can find these services by your library. 
    Then I call [DNSSD.resolve ](https://github.com/andriydruk/RxDNSSD/blob/master/dnssd/src/main/java/com/github/druk/dnssd/DNSSD.java#L226)and [DNSSD.queryRecord ](https://github.com/andriydruk/RxDNSSD/blob/master/dnssd/src/main/java/com/github/druk/dnssd/DNSSD.java#L401)to get service's ip and port.
    Finally, I use ip and port to establish connection with each service using SoketChannel and it works well.
               
   
   But I have some problems and need you to confirm.
    
1. Import your module to my project
![image](https://user-images.githubusercontent.com/12947669/51100525-76505e80-1811-11e9-8f00-31665684d588.png)

2. Reference your library.
![catch6c89](https://user-images.githubusercontent.com/12947669/51100641-ea8b0200-1811-11e9-8531-3dda905f14c1.jpg)
or 
![catch73b5](https://user-images.githubusercontent.com/12947669/51100658-f8d91e00-1811-11e9-9c45-4072d0670767.jpg)

   

I have two issues about your library:
        
    1. MulticastLock under-locked com.github.druk.dnssd.DNSSD
    2. Too many Open Files

   when I use implementation 'com.github.andriydruk:rx2dnssd:0.9.11' and I repeatly call DNSSD.browse() and DNSSDService.stop(),
   after a while crash occured 
   java.lang.RuntimeException: MulticastLock under-locked com.github.druk.dnssd.DNSSD
	at android.net.wifi.WifiManager$MulticastLock.release(WifiManager.java:2465)
	at com.github.druk.dnssd.DNSSD.onServiceStopped(DNSSD.java:578)
	at com.github.druk.dnssd.DNSSDBindable.onServiceStopped(DNSSDBindable.java:44)
	at com.github.druk.dnssd.InternalDNSSDService.stop(InternalDNSSDService.java:21)
	at com.linkplay.bonjour.presenter.LPBonjourServiceManager.stopLPBonjourDiscovery(LPBonjourServiceManager.java:187)
	at com.linkplay.dnssd.DNSSDActivity.stop(DNSSDActivity.java:184)
	at com.linkplay.dnssd.DNSSDActivity.access$300(DNSSDActivity.java:24)
	at com.linkplay.dnssd.DNSSDActivity$5.run(DNSSDActivity.java:157)
	at java.lang.Thread.run(Thread.java:831)

<br/>
   I believe this is caused by WifiManager.MulticastLock multicastLock in DNSSD.java

   The strange thing is this crash does not happend when I use implementation project(':rx2dnssd')

<br/>
<br/>

   when I use implementation project(':rx2dnssd') and I repeatly call DNSSD.browse() and DNSSDService.stop(),
   after a while Too many open files error comes out when I establish connection with service using ip and port.
               The strange thing is this crash does not happend when I use implementation 'com.github.andriydruk:rx2dnssd:0.9.11'
            

Is there any deference between implementation 'com.github.andriydruk:rx2dnssd:0.9.11' and implementation project(':rx2dnssd')？
Because I found this：
![image](https://user-images.githubusercontent.com/12947669/51100928-53bf4500-1813-11e9-94d1-f092babc0535.png)

![image](https://user-images.githubusercontent.com/12947669/51100935-65085180-1813-11e9-92f2-d80d0485f703.png)

**Comment by andriydruk** [comment]
Hi @dsliubao 
We have a problem with an unbalanced call at wifi multicast lock in 0.9.11. I'm now trying to fix it in master, but work hasn't finished yet.

For now, I would recommend the last stable version - 0.9.7. Please try this version with own wifi multicast-lock in your app.

**Comment by andriydruk** [comment]
Please check 0.9.12 build

**Comment by githubforzjm** [comment]
@andriydruk  I use 0.9.12 build in my project and it still not work

use 0.9.7 has never seen this crash

java.lang.RuntimeException: MulticastLock under-locked com.github.druk.dnssd.DNSSD
at android.net.wifi.WifiManager$MulticastLock.release(WifiManager.java:3390)
at com.github.druk.dnssd.DNSSD.onServiceStopped(DNSSD.java:578)
at com.github.druk.dnssd.DNSSDBindable.onServiceStopped(DNSSDBindable.java:44)
at com.github.druk.dnssd.InternalDNSSDService.stop(InternalDNSSDService.java:21)
at com.github.druk.dnssd.DNSSD.lambda$resolve$0(DNSSD.java:230)
at com.github.druk.dnssd.-$$Lambda$DNSSD$c9RIVhhcCfgpYtyUpMg_ToIEu6c.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6651)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)

**Comment by andriydruk** [comment]
Hm, it looks very weird. You stacktrace looks like from the previous version of RxDNSSD - 0.9.11.

`InternalDNSSDService` should call `DNSSDBindable.onServiceStopped` at line 24
![screen shot 2019-01-25 at 10 13 58 am](https://user-images.githubusercontent.com/1927559/51733491-1caa2880-208a-11e9-8619-d7e8e8ef659a.png)

At your stackrace this call at line 21, like in dnssd 0.9.11

Do you use gradle for dependency managment? Could you confirm that you have dnssd version 0.9.12 in your gradle dependency graph, please

**Comment by andriydruk** [comment]
@githubforzjm another problem can occur with Samsung - they broke bindable version from time to time. Last time this happened in Android 4.2.1 build. Maybe they did it again.
Please try the embedded version with this device (0.9.13). It starts a little bit slower but should work at any device.

**Comment by githubforzjm** [comment]
@andriydruk Although service discovery is a little bit slower than previous version 0.9.12, but it looks like it solves the issue by using embedded version 0.9.13. （**I have to called stop  discovery when phone's Wi-Fi was disconnected and start discovery again when phone's Wi-Fi reconnect to my office network**）

But Service is still not found when I turn off wifi and turn on wifi immediately and the phone reconnects to my office network within a few seconds. 

The log is as follows:
2019-02-13 16:35:47.312 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: post exit
2019-02-13 16:35:50.549 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started
2019-02-13 16:35:50.551 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: post exit
2019-02-13 16:35:50.553 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started
2019-02-13 16:35:50.555 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: post exit
2019-02-13 16:35:50.557 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started

<br/>
If I turn off wifi and turn on wifi after a few secons (about 4~5 seconds), service discovery is normal.
<br/>

The log is as follows:
<br/>
2019-02-13 16:34:05.431 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: post exit
2019-02-13 16:34:12.240 4154-4217/com.linkplay.bonjour I/DNSSDEmbedded: finish with code: 4
2019-02-13 16:34:14.231 4154-7287/com.linkplay.bonjour I/DNSSDEmbedded: init
2019-02-13 16:34:14.237 4154-7287/com.linkplay.bonjour I/DNSSDEmbedded: start
2019-02-13 16:34:14.239 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: post exit
2019-02-13 16:34:14.241 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started
2019-02-13 16:34:14.243 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: post exit
2019-02-13 16:34:14.244 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started
2019-02-13 16:34:14.331 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started
2019-02-13 16:34:14.334 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started
2019-02-13 16:34:14.573 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started
2019-02-13 16:34:14.590 4154-4154/com.linkplay.bonjour I/DNSSDEmbedded: already started
<br/>
<br/>
Look at code and there's Handler#postDelayed about 5 sencons to invoke a native method

![image](https://user-images.githubusercontent.com/12947669/52698224-08cd5480-2fae-11e9-969f-990451f3f537.png)

![image](https://user-images.githubusercontent.com/12947669/52698250-1387e980-2fae-11e9-9741-227617d23814.png)

**Comment by andriydruk** [comment]
I see, probably we should handle WIFI inside the library.
For now, you can change this mStopTimerDelay through DNSSDEmbedded constructor. 
Please try change it to 0.
