### ISSUE TITLE
Process UTF-8 error.

### ISSUE THREAD

**Issue by NeoLSN** [andriydruk/RxDNSSD#6]
I saw this log on Android Logcat monitor.
It seems Apple library's error. Can we avoid that?
```
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x5c
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]     string: '�\011.local.'
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]     in call to NewStringUTF
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]     from int com.apple.dnssd.AppleService.ProcessResults()
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65] "Thread-4536" prio=5 tid=19 Runnable
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x130560e0 self=0x9f61c400
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | sysTid=12468 nice=-11 cgrp=apps sched=0/0 handle=0x9f630080
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 1027083 0 1 ) utm=0 stm=0 core=2 HZ=100
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | stack=0x9f3fa000-0x9f3fc000 stackSize=1036KB
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #00 pc 00004640  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #01 pc 00002e8d  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #02 pc 00248069  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #03 pc 0022c9f3  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+146)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #04 pc 000b1873  /system/lib/libart.so (art::JniAbort(char const*, char const*)+582)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #05 pc 000b1fad  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #06 pc 000b4407  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.128)+882)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #07 pc 000bce71  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+36)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #08 pc 00004915  /data/app/com.hitachi.smartac-1/lib/arm/libjdns_sd.so (???)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #09 pc 00002961  /data/app/com.hitachi.smartac-1/lib/arm/libjdns_sd.so (???)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #10 pc 000031c5  /data/app/com.hitachi.smartac-1/lib/arm/libjdns_sd.so (DNSServiceProcessResult+308)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #11 pc 00004e89  /data/app/com.hitachi.smartac-1/lib/arm/libjdns_sd.so (Java_com_apple_dnssd_AppleService_ProcessResults+152)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #12 pc 002d7d8b  /data/dalvik-cache/arm/data@app@com.hitachi.smartac-1@base.apk@classes.dex (Java_com_apple_dnssd_AppleService_ProcessResults__+82)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   at com.apple.dnssd.AppleService.ProcessResults(Native method)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   at com.apple.dnssd.AppleService.run(DNSSD.java:693)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   - locked <0x256d48d0> (a com.apple.dnssd.AppleResolver)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   at java.lang.Thread.run(Thread.java:818)
07-15 16:21:47.139 12420-12468/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65] 
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x5c
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]     string: '�\011.local.'
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]     in call to NewStringUTF
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]     from int com.apple.dnssd.AppleService.ProcessResults()
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65] "Thread-4538" prio=5 tid=21 Runnable
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x13065080 self=0xaf14b800
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | sysTid=12470 nice=-11 cgrp=apps sched=0/0 handle=0xaf15ad00
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 653594 271614 3 ) utm=0 stm=0 core=0 HZ=100
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | stack=0x9f1f2000-0x9f1f4000 stackSize=1036KB
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #00 pc 00004640  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #01 pc 00002e8d  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #02 pc 00248069  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #03 pc 0022c9f3  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+146)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #04 pc 000b1873  /system/lib/libart.so (art::JniAbort(char const*, char const*)+582)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #05 pc 000b1fad  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #06 pc 000b4407  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.128)+882)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #07 pc 000bce71  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+36)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #08 pc 00004915  /data/app/com.hitachi.smartac-1/lib/arm/libjdns_sd.so (???)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #09 pc 00002961  /data/app/com.hitachi.smartac-1/lib/arm/libjdns_sd.so (???)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #10 pc 000031c5  /data/app/com.hitachi.smartac-1/lib/arm/libjdns_sd.so (DNSServiceProcessResult+308)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #11 pc 00004e89  /data/app/com.hitachi.smartac-1/lib/arm/libjdns_sd.so (Java_com_apple_dnssd_AppleService_ProcessResults+152)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   native: #12 pc 002d7d8b  /data/dalvik-cache/arm/data@app@com.hitachi.smartac-1@base.apk@classes.dex (Java_com_apple_dnssd_AppleService_ProcessResults__+82)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   at com.apple.dnssd.AppleService.ProcessResults(Native method)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   at com.apple.dnssd.AppleService.run(DNSSD.java:693)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   - locked <0x1c9790c9> (a com.apple.dnssd.AppleResolver)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65]   at java.lang.Thread.run(Thread.java:818)
07-15 16:21:47.139 12420-12470/com.hitachi.smartac A/art: art/runtime/check_jni.cc:65] 
07-15 16:21:47.159 12420-12468/com.hitachi.smartac A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x6f0068b2 in tid 12468 (Thread-4536)

```

**Comment by andriydruk** [comment]
Hm, it looks like a bug in Android  UTF-8 converting. 
Do you have steps to reproduce this issue? Maybe some unusual characters in service name, domain, etc.

**Comment by NeoLSN** [comment]
It happened when you are trying to scan nearby mDns devices. So I don't know which mDns device caused this problem.
