### ISSUE TITLE
Have problems with implementation project(':rx2dnssd') and implementaion 'com.github.andriydruk:rx2dnssd:0.9.11'

### ISSUE THREAD

**Issue by dsliubao** [andriydruk/RxDNSSD#60]
I am almost same with [this question](https://github.com/andriydruk/RxDNSSD/issues/59)

I use the same code in your [dnssdsamples.DNSSDActivity.java](https://github.com/andriydruk/RxDNSSD/blob/master/app/src/main/java/com/github/druk/dnssdsamples/DNSSDActivity.java) to discovery service with specific type.

    class TestThread extends Thread {
        @Override
        public void run() {
            for (int i = 0; i < 100; i++) {
                start_browse();// start browse

                ThreadUtils.sleep(5000);

                stop_browse();// stop browse

                ThreadUtils.sleep(3000);
            }
        }
    }

I import your library by **implementation project(':rx2dnssd')**

I create a thread to test the discovery of service，but if there are 30 services on my office network
After calling start_browse() and stop_browse() about 15 times （if there are 20 services， about 23 times），resolve a service or Query for an arbitrary DNS record has an error that said **DNS-SD Error -65539: NO_MEMORY** and I have to kill the app to discovery services again.

The strange thing is that this error did not showup when I use your library by **implementation 'com.github.andriydruk:rx2dnssd:0.9.11'**

But when I use your library by **implementation 'com.github.andriydruk:rx2dnssd:0.9.11'** a crash happened which did not appear when I use your librar by **implementation project(':rx2dnssd')**
   
    java.lang.RuntimeException: MulticastLock under-locked com.github.druk.dnssd.DNSSD
	at android.net.wifi.WifiManager$MulticastLock.release(WifiManager.java:3390)
	at com.github.druk.dnssd.DNSSD.onServiceStopped(DNSSD.java:578)
	at com.github.druk.dnssd.DNSSDBindable.onServiceStopped(DNSSDBindable.java:44)
	at com.github.druk.dnssd.InternalDNSSDService.stop(InternalDNSSDService.java:21)
	at com.linkplay.bonjour.presenter.LPBonjourServiceManager.stopLPBonjourDiscovery(LPBonjourServiceManager.java:187)
	at com.linkplay.dnssd.DNSSDActivity.stop_browse(DNSSDActivity.java:137)
	at com.linkplay.dnssd.DNSSDActivity.access$400(DNSSDActivity.java:22)
	at com.linkplay.dnssd.DNSSDActivity$TestThread.run(DNSSDActivity.java:163)

I found some deference between **implementation project(':rx2dnssd')** and **implementation 'com.github.andriydruk:rx2dnssd:0.9.11'**  in this [DNSSD.java](https://github.com/andriydruk/RxDNSSD/blob/master/dnssd/src/main/java/com/github/druk/dnssd/DNSSD.java)

![image](https://user-images.githubusercontent.com/12947669/51162425-14572e00-18d1-11e9-8ca5-1c746cb0b700.png)

![image](https://user-images.githubusercontent.com/12947669/51162451-2df87580-18d1-11e9-81ea-78637896446b.png)

**Comment by andriydruk** [comment]
Hi @dsliubao 
We have a problem with an unbalanced call at wifi multicast lock in 0.9.11. I'm now trying to fix it in master, but work hasn't finished yet.

For now, I would recommend the last stable version - 0.9.7. Please try this version with own wifi multicast-lock in your app.

**Comment by andriydruk** [comment]
Please check 0.9.12 build

**Comment by githubforzjm** [comment]
@andriydruk I use 0.9.12 build in my project and it still not work

java.lang.RuntimeException: MulticastLock under-locked com.github.druk.dnssd.DNSSD
	at android.net.wifi.WifiManager$MulticastLock.release(WifiManager.java:3390)
	at com.github.druk.dnssd.DNSSD.onServiceStopped(DNSSD.java:578)
	at com.github.druk.dnssd.DNSSDBindable.onServiceStopped(DNSSDBindable.java:44)
	at com.github.druk.dnssd.InternalDNSSDService.stop(InternalDNSSDService.java:21)
	at com.github.druk.dnssd.DNSSD.lambda$resolve$0(DNSSD.java:230)
	at com.github.druk.dnssd.-$$Lambda$DNSSD$c9RIVhhcCfgpYtyUpMg_ToIEu6c.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)

**Comment by andriydruk** [comment]
I'm closing because it duplicates #59
