### ISSUE TITLE
Discovery on Android 9 doesn't work

### ISSUE THREAD

**Issue by JKorsten** [andriydruk/RxDNSSD#65]
I've seen this  #54 and other issues and tried the mentioned solutions but it doesn't work for me. I'm using implementation 'com.github.andriydruk:rx2dnssd:0.9.13'

When I run the following code

`rxDnssd.browse("correct service type", "local.").compose(rxDnssd.resolve()).compose(rxDnssd.queryRecords()).subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).subscribe();`

I get following exception:

`2019-02-14 14:05:20.147 12438-12480/? E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    Process: com.prowise.reflectandroidclient, PID: 12438
    io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: Interrupted wait at init
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:276)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:75)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableDoFinally.subscribeActual(FlowableDoFinally.java:46)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.Flowable.subscribe(Flowable.java:14425)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: Interrupted wait at init
        at android.net.nsd.NsdManager.fatal(NsdManager.java:498)
        at android.net.nsd.NsdManager.init(NsdManager.java:492)
        at android.net.nsd.NsdManager.<init>(NsdManager.java:271)
        at android.app.SystemServiceRegistry$29.createService(SystemServiceRegistry.java:437)
        at android.app.SystemServiceRegistry$29.createService(SystemServiceRegistry.java:432)
        at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1166)
        at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1082)
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1739)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:728)
        at com.github.druk.dnssd.DNSSDBindable.onServiceStarting(DNSSDBindable.java:39)
        at com.github.druk.dnssd.DNSSD.browse(DNSSD.java:140)
        at com.github.druk.rx2dnssd.Rx2DnssdCommon.lambda$browse$0$Rx2DnssdCommon(Rx2DnssdCommon.java:50)
        at com.github.druk.rx2dnssd.Rx2DnssdCommon$$Lambda$0.getService(Unknown Source:6)
        at com.github.druk.rx2dnssd.Rx2DnssdCommon$DNSSDServiceAction.subscribe(Rx2DnssdCommon.java:247)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableDoFinally.subscribeActual(FlowableDoFinally.java:46) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14425) 
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-02-14 14:15:07.376 12947-12989/com.prowise.reflectandroidclient E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
    Process: com.prowise.reflectandroidclient, PID: 12947
    io.reactivex.exceptions.UndeliverableException: java.lang.RuntimeException: Interrupted wait at init
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:276)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:75)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableDoFinally.subscribeActual(FlowableDoFinally.java:46)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478)
        at io.reactivex.Flowable.subscribe(Flowable.java:14425)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: Interrupted wait at init
        at android.net.nsd.NsdManager.fatal(NsdManager.java:498)
        at android.net.nsd.NsdManager.init(NsdManager.java:492)
        at android.net.nsd.NsdManager.<init>(NsdManager.java:271)
        at android.app.SystemServiceRegistry$29.createService(SystemServiceRegistry.java:437)
        at android.app.SystemServiceRegistry$29.createService(SystemServiceRegistry.java:432)
        at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1166)
        at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1082)
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1739)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:728)
        at com.github.druk.dnssd.DNSSDBindable.onServiceStarting(DNSSDBindable.java:39)
        at com.github.druk.dnssd.DNSSD.browse(DNSSD.java:140)
        at com.github.druk.rx2dnssd.Rx2DnssdCommon.lambda$browse$0$Rx2DnssdCommon(Rx2DnssdCommon.java:50)
        at com.github.druk.rx2dnssd.Rx2DnssdCommon$$Lambda$0.getService(Unknown Source:6)
        at com.github.druk.rx2dnssd.Rx2DnssdCommon$DNSSDServiceAction.subscribe(Rx2DnssdCommon.java:247)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableDoFinally.subscribeActual(FlowableDoFinally.java:46) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.internal.operators.flowable.FlowableFlatMap.subscribeActual(FlowableFlatMap.java:53) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14478) 
        at io.reactivex.Flowable.subscribe(Flowable.java:14425) 
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) `

On other android versions (older) it works.

**Comment by JKorsten** [comment]
Some extra information, I'm testing it on a OnePlus 6 with android version 9 and OxygenOS version 9.0.3

**Comment by andriydruk** [comment]
Looks like something bad happened in OS
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/net/nsd/NsdManager.java#492
This command crash, try it in your OnePlus 6
```
context.getSystemService(Context.NSD_SERVICE);
```

Or try embedded version, it doesn't call NSD_SERVICE

**Comment by JKorsten** [comment]
Using the embedded version works. Thank you very much.
