### ISSUE TITLE
Build Error when run apps with your library 

### ISSUE THREAD

**Issue by githubforzjm** [andriydruk/RxDNSSD#67]
@andriydruk I used your library in my test code before and it work fine.
Recently, I use your library in my project which contains a lot of methods and I have already configured build.gradle file like this
![image](https://user-images.githubusercontent.com/12947669/54977604-d49b7980-4fd8-11e9-930a-c71c7b3141a4.png)
![image](https://user-images.githubusercontent.com/12947669/54977673-07457200-4fd9-11e9-97c1-25b5a4ee5813.png)

After add **compile 'com.github.andriydruk:rx2dnssd:0.9.13'** in my project's build.gradle, 
 I can compile but when I want to deploy to real phone I get Error Return code 1 for dex process and te following log stack.

The error message from Build: 

    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':Wiimu:transformClassesWithDexForMuzoDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)

    Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\ZJM\.android\build-cache\7c2ad348c7df74776c6392185f01eb79a67d0283\output\jars\classes.jar' to 'E:\Muzo4.0\android\Wiimu\build\intermediates\transforms\dex\Muzo\debug\folders\1000\10\classes_491fa8397b2d56e56f9f2527882fbb34614b9388'
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more

    Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\ZJM\.android\build-cache\7c2ad348c7df74776c6392185f01eb79a67d0283\output\jars\classes.jar' to 'E:\Muzo4.0\android\Wiimu\build\intermediates\transforms\dex\Muzo\debug\folders\1000\10\classes_491fa8397b2d56e56f9f2527882fbb34614b9388'
	at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:453)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 48 more

    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\ZJM\.android\build-cache\7c2ad348c7df74776c6392185f01eb79a67d0283\output\jars\classes.jar' to 'E:\Muzo4.0\android\Wiimu\build\intermediates\transforms\dex\Muzo\debug\folders\1000\10\classes_491fa8397b2d56e56f9f2527882fbb34614b9388'
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:147)
	at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:408)
	... 51 more

    Caused by: java.lang.RuntimeException: Unable to pre-dex 'C:\Users\ZJM\.android\build-cache\7c2ad348c7df74776c6392185f01eb79a67d0283\output\jars\classes.jar' to 'E:\Muzo4.0\android\Wiimu\build\intermediates\transforms\dex\Muzo\debug\folders\1000\10\classes_491fa8397b2d56e56f9f2527882fbb34614b9388'
	at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.call(DexTransform.java:521)
	at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.call(DexTransform.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

    Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:680)
	at com.android.builder.utils.FileCache.doLocked(FileCache.java:639)
	at com.android.builder.utils.FileCache.queryCacheEntry(FileCache.java:395)
	at com.android.builder.utils.FileCache.createFile(FileCache.java:290)
	at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.call(DexTransform.java:518)
	... 7 more

    Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:680)
	at com.android.builder.utils.FileCache.doLocked(FileCache.java:639)
	at com.android.builder.utils.FileCache.lambda$queryCacheEntry$10(FileCache.java:419)
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:678)
	... 11 more

    Caused by: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:680)
	at com.android.builder.utils.FileCache.doLocked(FileCache.java:639)
	at com.android.builder.utils.FileCache.lambda$createFile$5(FileCache.java:282)
	at com.android.builder.utils.FileCache.lambda$null$9(FileCache.java:440)
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:678)
	... 14 more

    Caused by: com.android.builder.utils.FileCache$FileCreatorException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.utils.FileCache.lambda$createFile$0(FileCache.java:241)
	at com.android.builder.utils.FileCache.lambda$null$4(FileCache.java:285)
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:678)
	... 18 more

    Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:180)
	at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:158)
	at com.android.builder.core.AndroidBuilder.preDexLibraryNoCache(AndroidBuilder.java:1464)
	at com.android.builder.internal.compiler.PreDexCache.preDexLibrary(PreDexCache.java:129)
	at com.android.builder.core.AndroidBuilder.preDexLibrary(AndroidBuilder.java:1415)
	at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.lambda$call$0(DexTransform.java:503)
	at com.android.builder.utils.FileCache.lambda$createFile$0(FileCache.java:239)
	... 20 more

    Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:178)
	... 26 more

    Caused by: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.internal.compiler.DexWrapper$DexProcessResult.assertNormalExitValue(DexWrapper.java:117)
	at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:175)
	... 4 more

Finally, I tried use your source code [dnssd]( http://jcenter.bintray.com/com/github/andriydruk/dnssd/0.9.13/), [rx2dnssd](http://jcenter.bintray.com/com/github/andriydruk/rx2dnssd/0.9.13/) and [jni source code](https://github.com/andriydruk/RxDNSSD/tree/master/dnssd/src/main/jni) in my project and it work fine!
**Is there a good solution to this situation?** 

![image](https://user-images.githubusercontent.com/12947669/54978574-aff4d100-4fdb-11e9-9d73-2a106edb4ed7.png)
![image](https://user-images.githubusercontent.com/12947669/54978658-ef232200-4fdb-11e9-96f7-c90726afe04a.png)

**Comment by githubforzjm** [comment]
this is my project's androidDependencies
[androidDependencies.txt](https://github.com/andriydruk/RxDNSSD/files/3007491/androidDependencies.txt)
