### ISSUE TITLE
UnsupportedOperationException: Exceeded maximum number of wifi locks

### ISSUE THREAD

**Issue by anthowm** [andriydruk/RxDNSSD#97]
Hi after alot discoveries this exception is triggered anyone know how to fix it ?
java.lang.UnsupportedOperationException: Exceeded maximum number of wifi locks
    at android.net.wifi.WifiManager$MulticastLock.acquire(WifiManager.java:4911)
    at com.github.druk.dnssd.DNSSD.onServiceStarting(DNSSD.java:569)
    at com.github.druk.dnssd.DNSSDBindable.onServiceStarting(DNSSDBindable.java:38)
    at com.github.druk.dnssd.DNSSD.queryRecord(DNSSD.java:412)
    at com.github.druk.dnssd.DNSSD.queryRecord(DNSSD.java:408)
    at com.example.sweeprapitest.Discovery.BonjourDiscovery.startQueryRecords(BonjourDiscovery.java:255)
    at com.example.sweeprapitest.Discovery.BonjourDiscovery.access$300(BonjourDiscovery.java:28)
    at com.example.sweeprapitest.Discovery.BonjourDiscovery$3.serviceResolved(BonjourDiscovery.java:205)
    at com.github.druk.dnssd.DNSSD$2.lambda$serviceResolved$0(DNSSD.java:240)
    at com.github.druk.dnssd.-$$Lambda$DNSSD$2$0OhPKoqzFsN_3_yfNshD9HEzVL4.run
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by andriydruk** [comment]
Hi, you probably create new DNSSD for every discovery and never stop them. 
Locks should be released here:
https://github.com/andriydruk/RxDNSSD/blob/master/dnssd/src/main/java/com/github/druk/dnssd/DNSSD.java#L578

Try to use one shared DNSSD object

**Comment by anthowm** [comment]
thanks that solve my problem. !
